### ISSUE TITLE
Action type uppercase

### ISSUE THREAD

**Issue by onrige** [svagi/redux-routines#1]
Hey. Just a question. Why do you transform action type string to uppercase? It looks like a surplus operation in my opinion.

**Comment by svagi** [comment]
Hey @onrige. Basically it is a way to distinguish between a action type and action creator. Action type is a string which uniquely identifies the action, while action creator is a function returning an action object. It is a common practice that constants are uppercase, while functions are smallercase. See http://redux.js.org/docs/basics/Actions.html

**Comment by onrige** [comment]
@svagi Sure, i know it. But my question is about more complex applications rather than in Redux Basics. In more complex applications there is a something about best practice to prefix all actions by feature. For example let's take a look at redux-persist. They added to all actions 'persist/' prefix. Or for example I want to add 'home/' prefix to my application reducer, but with your library I can't do it because of uppercase (yes, I want exactly lower). Or let's take a look at redux-actions (best example) - they don't apply uppercase to actions, so...Of cause this prefix can be in uppercase too, but I don't understand why did you decided it for everyone :)

**Comment by svagi** [comment]
@onrige Fair point. The main reason I used uppercase is because I wanted to remain consistent with the suffix, which is also uppercase. However, it is true that this choice should be on the user. Anyway, the suffix can not be changed, the question is whether we should allow the user to change it or not. 

I think we should do 2 things, remove uppercase for the prefix and change suffix separator to something more distinguishable (for example `/SUFFIX` instead of `_SUFFIX`). What do you think? Would you like to create a PR?

**Comment by onrige** [comment]
Sure, I can make a PR. But I think there is no need to change suffix. In my opinion it must depends only on developer because may be someone will need to create action with such names for example: `createRoutine(APP_FETCH)`, `createRoutine(app/FETCH)`, `createRoutine(APP/FETCH)`, `createRoutine(@@app/FETCH)` and so on.

**Comment by svagi** [comment]
@onrige When I was talking about suffix I ment string that represent type of the action (e.g. `_TRIGGER`, `_REQUEST`, ...). Anyway, thanks for the PR. 👍

**Comment by onrige** [comment]
@svagi  I think there is no need to change suffix to something else, it's ok. You are welcome :)
