### ISSUE TITLE
Merge with redux-saga-routines

### ISSUE THREAD

**Issue by afitiskin** [svagi/redux-routines#3]
Hello @svagi! I'm the author of [redux-saga-routines](https://github.com/afitiskin/redux-saga-routines) package. As you can see, our packages are almost similar (i think you package are based on my ideas). I'd like to divide my package into `redux-routines` and `redux-form-saga-routines`. 

What do you think, if we take my implementation of routines (based on [redux-actions](https://github.com/reduxactions/redux-actions)) for `redux-routines` package?

**Comment by afitiskin** [comment]
[Here is my implementation](https://github.com/afitiskin/redux-saga-routines/blob/master/src/createRoutine.js) of `createRoutine` function

**Comment by svagi** [comment]
Hi @afitiskin. These ideas aren't new, but it's true that I tried your library first. Separation of concerns is the main reason why I created my own implementation, thus I think it's good idea to cooperate.

Your implementation looks good (maybe this [line](https://github.com/afitiskin/redux-saga-routines/blob/master/src/createRoutine.js#L15) can be just `{}`?) and I'm ok with that, but it means breaking change for this library because I'm using `enhancer` of the whole action instead of `payloadCreator`.

Let's use your new implementation with the new major release of `redux-routines` that will be [FSA](https://github.com/acdlite/flux-standard-action) compatible. Would you like to create a PR?

**Comment by amok** [comment]
any news on this, guys :) ?

**Comment by svagi** [comment]
Hey @amok v3 is coming, but it needs some code review and testing.

**Comment by svagi** [comment]
Closed by #4
